#
# This tests the extension-ci-tools works as expected
#
name: Test CI Tools
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
#  extension-template-main:
#    name: Extension template
#    uses: ./.github/workflows/_extension_distribution.yml
#    with:
#      extension_name: quack
#      override_repository: duckdb/extension-template
#      override_ref: main
#      duckdb_version: v1.0.0
#      override_ci_tools_repository: ${{ github.repository }}
#      override_ci_tools_ref: ${{ github.sha }}

  delta-extension-main:
    name: Rust builds (using Delta extension)
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      extension_name: delta
      override_repository: duckdb/duckdb_delta
      override_ref: main
      override_ci_tools_repository: ${{ github.repository }}
      override_ci_tools_ref: ${{ github.sha }}
      duckdb_version: v1.0.0
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
      extra_toolchains: 'rust'